version: '3.2'

services:
  sql-server:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
    networks:
      - public
  talend:
    image: talend/tac:latest
    container_name: talend
    ports:
      - "8080:8080"
    environment:
      - TAC_ADMIN_USER=admin
      - TAC_ADMIN_PASS=admin
    depends_on:
      - sql-server
    networks:
      - public

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    networks:
      - public


networks:
  - public 