version: '3.2'

services:
  sql-server:
    container_name: sql-server-db
    build:
    
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: AlexisBG#123
      ACCEPT_EULA: "Y"
    networks:
      - public
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "alexisbg"
    ports:
      - "3306:3306"
    networks:
      - public


networks:
  public: